package clases;
public class Cabecera_usuario_registrado extends Cabecera_comun {
	public Usuario_registrado _usuario_registrado;
	public Buscar_elementos _buscar_elementos;
	public Ver_perfil_propio_usuario_registrado _ver_perfil_propio_usuario_registrado;
}