package clases;
public class ContenedorSus_Listas extends Contenedor_modificar_listados {
	public Ver_perfil_del_artista_ajeno _ver_perfil_del_artista_ajeno;
	public Sus_listas_de_reproduccion _sus_listas_de_reproduccion;
}