package clases;
public class Lista_de_reproduccion_perfil_ajeno extends vistas.VistaLista_de_reproduccion_perfil_ajeno {
//	private Label _nombre_ListasL;
	public Listas_de_reproduccion_perfil_ajeno _listas_de_reproduccion_perfil_ajeno;
	public Ver_lista_de_reproduccion_ajena _ver_lista_de_reproduccion_ajena;
}